name: dart_translate
version: 1.0.2
description: Google translate
homepage: https://github.com/mrpond/google-dart-translator
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  http: ^0.13.1
dev_dependencies:
  test: '>=1.15.0 <2.0.0'